ALTER TABLE fgp_dsx_dm.kaspi_merchants
ADD COLUMN brand varchar(100),
ADD COLUMN articul varchar(100),
ADD COLUMN sales_per_day numeric,
ADD COLUMN price numeric,
ADD COLUMN rating numeric,
ADD COLUMN reviews_count numeric,
ADD COLUMN is_new_data boolean NOT NULL DEFAULT false;


Продавцы_в_категории_ТВ,_Аудио,_Видео
Продавцы_в_категории_Товары_для_дома_и_дачи
Продавцы_в_категории_Телефоны_и_гаджеты
Продавцы_в_категории_Товары_для_дома_и_дачи
Продавцы_в_категории_Бытовая_техника
Продавцы_в_категории_Детские_товары
Продавцы_в_категории_Компьютеры
Продавцы_в_категории_Красота_и_здоровье
Продавцы_в_категории_Мебель
